# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JHMemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JHMemo
    pod 'FMDB'
    pod 'Kingfisher'
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'lottie-ios'
		pod 'SwiftLint'
		pod 'KeychainSwift'
		pod 'Kingfisher/SwiftUI'
	
	target 'MemoGroupExtension' do
		# Pods for testing
	end

end
